### ISSUE TITLE
Help offered

### ISSUE THREAD

**Issue by willis7** [delphix-integrations/terraform-provider-delphix#1]
I work for a company which is a customer and I'm keen to use the solution you are building. How can I help to make this happen?

If you have a development environment, I would be keen to start working on some features.

**Comment by arunskurian** [comment]
@willis7, 
Thank you for reaching out and our apologies for the long delay in responding.

**Comment by arunskurian** [comment]
Hi @willis7 , 
Apologies for the really delayed response. Delphix is working on a new terraform provider and we plan to release it in the near future. We appreciate the offer to collaborate on features and will keep you posted on the progress.

**Comment by nick-mathison** [comment]
If you are looking to make contributions, feel free to fork the repository and follow the README instructions to build the provider locally. 

If you have anything you would specifically like to build or code you'd like to submit, please create an issue and tag me. I'll see what we can do!
