### ISSUE TITLE
2020-06-24 Go get failing with error

### ISSUE THREAD

**Issue by smackmybitsup** [delphix-integrations/terraform-provider-delphix#2]
following the instructions in the readme.md to build the provider leads to error output and no provider is output.

    1  export GOPATH=`pwd`
    2  cd src/terraform-provider-delphix/
    3  go get
    4  go build

```
root@75f5f1e8488a:/go/src/terraform-provider-delphix# go get
# github.com/delphix/delphix-go-sdk
/go/pkg/mod/github.com/delphix/delphix-go-sdk@v0.0.0-20190313140812-a1473ec93fc2/delphix_funcs.go:107:23: obj.Result undefined (type []interface {} has no field or method Result)
```

**Version**
```
root@75f5f1e8488a:/go/src/terraform-provider-delphix# go version
go version go1.14.4 linux/amd64
```

**Additional Context**

**Comment by arunskurian** [comment]
Hi @smackmybitsup , 
Apologies for the delayed response to your comment. We are revamping the terraform provider for Delphix and are currently working on a brand new provider thats expected to be live in the near future. I'd suggest you check back in a few weeks time for the updates.
